"""Build bilingual static posts and indexes. Run from any directory with Python 3.10+."""
from datetime import date, datetime, timezone
from email.utils import format_datetime
from html import escape
from html.parser import HTMLParser
from pathlib import Path
from string import Template
import argparse
import json
import math
import re
import sys
import xml.etree.ElementTree as ET

import markdown

ROOT = Path(__file__).resolve().parent.parent
BASE = 'https://theodoruszq.github.io'
LANGS = {'zh': 'zh-Hans', 'en': 'en'}
GENERATED = '<!-- Generated by scripts/build_posts.py; edit content/posts and templates instead. -->'
SLUG = re.compile(r'[a-z0-9][a-z0-9_-]*\Z')

class PlainText(HTMLParser):
    def __init__(self):
        super().__init__(); self.parts = []
    def handle_data(self, data):
        self.parts.append(data)

def plain(html):
    parser = PlainText(); parser.feed(html)
    return ''.join(parser.parts)

def url(slug, lang):
    return f'{"/en" if lang == "en" else ""}/posts/{slug}/'

def text_attrs(values):
    return ' '.join(f'data-text-{lang}="{escape(values[lang], quote=True)}"' for lang in LANGS)

def href_attrs(values):
    return ' '.join(f'data-href-{lang}="{escape(values[lang], quote=True)}"' for lang in LANGS)

def load_posts(root):
    posts = []
    for folder in sorted((root / 'content/posts').iterdir()):
        if not folder.is_dir() or folder.name.startswith('.'):
            continue
        if not SLUG.fullmatch(folder.name):
            raise ValueError(f'Invalid post folder: {folder.name}')
        meta = json.loads((folder / 'post.json').read_text())
        if not isinstance(meta.get('draft'), bool):
            raise ValueError(f'{folder.name}: draft must be true or false')
        if meta['draft']:
            continue
        post = {**meta, 'slug': folder.name, 'body': {}, 'minutes': {}}
        date.fromisoformat(post['date'])
        published = post.get('published', post['date'] + 'T00:00:00+08:00')
        dt = datetime.fromisoformat(published)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        post['published'] = dt.isoformat()
        for key in ['image', 'original']:
            value = post.get(key, '')
            if not isinstance(value, str):
                raise ValueError(f'{folder.name}: {key} must be a string')
            if value and key == 'image':
                candidate = (root / value.lstrip('/')).resolve()
                if not value.startswith('/') or value.startswith('//') or not candidate.is_relative_to(root.resolve()) or not candidate.is_file():
                    raise ValueError(f'{folder.name}: image must refer to an existing local file')
            if value and key == 'original' and not value.startswith('https://'):
                raise ValueError(f'{folder.name}: original must be an HTTPS URL')
        for lang in LANGS:
            for field in ['title', 'summary']:
                value = post.get(field, {}).get(lang, '')
                if not isinstance(value, str) or not value.strip() or 'TODO' in value:
                    raise ValueError(f'{folder.name}: complete {field}.{lang} before publishing')
            source = (folder / f'{lang}.md').read_text()
            if not source.strip() or 'TODO' in source:
                raise ValueError(f'{folder.name}: complete {lang}.md before publishing')
            body = markdown.markdown(source, extensions=['extra', 'toc'], output_format='html')
            post['body'][lang] = body
            words = plain(body)
            post['minutes'][lang] = max(1, math.ceil(len(re.findall(r'[\u4e00-\u9fff]', words))/350 + len(re.findall(r'[A-Za-z0-9]+', words))/200))
        posts.append(post)
    return sorted(posts, key=lambda p: (p['date'], p['slug']), reverse=True)

def article(post, lang, active):
    title = escape(post['title'][lang])
    reading = post['minutes'][lang]
    reading_label = f'{reading} 分钟' if lang == 'zh' else f'{reading} min read'
    back = '← 返回博客' if lang == 'zh' else '← Blogs'
    source = ''
    if post.get('original'):
        label = '最初发布于 WordPress' if lang == 'zh' else 'Originally published on WordPress'
        source = f'<p class="post-source"><a href="{escape(post["original"], quote=True)}" data-i18n="originalPost">{label}</a></p>'
    hidden = '' if active else ' hidden'
    body = re.sub(r'(?<![\w-])id="([^"]+)"', lambda match: f'data-anchor-id="{match[1]}" id="{match[1] if active else lang + "--" + match[1]}"', post['body'][lang])
    return f'''<article class="post" data-translation="{lang}" lang="{LANGS[lang]}"{hidden}>
        <header class="post-header">
          <a class="back-link" href="/posts/" data-i18n="backBlogs">{back}</a>
          <h1>{title}</h1>
          <p class="entry-meta"><time data-ui-date datetime="{post['date']}">{post['date']}</time> · <span data-reading-minutes="{reading}">{reading_label}</span></p>
        </header>
        <div class="post-body" lang="{LANGS[lang]}">
{body}
        </div>
{source}
        <nav class="post-end" aria-label="{'文章导航' if lang == 'zh' else 'Article navigation'}" data-i18n-aria-label="postNavigation"><a href="/posts/" data-i18n="backBlogs">{back}</a></nav>
      </article>'''

def render_page(post, lang, template):
    urls = {key: url(post['slug'], key) for key in LANGS}
    titles = {key: post['title'][key] + ' · Digital Reality' for key in LANGS}
    title = escape(post['title'][lang]); summary = escape(post['summary'][lang], quote=True)
    head = f'''  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#ffffff">
  <title {text_attrs(titles)}>{escape(titles[lang])}</title>
  <meta name="description" content="{summary}" data-content-zh="{escape(post['summary']['zh'], quote=True)}" data-content-en="{escape(post['summary']['en'], quote=True)}">
  <meta name="author" content="Theodorus Zhou">
  <link rel="canonical" href="{BASE + urls[lang]}" {href_attrs({key: BASE + value for key, value in urls.items()})}>
  <link rel="alternate" hreflang="zh-Hans" href="{BASE + urls['zh']}">
  <link rel="alternate" hreflang="en" href="{BASE + urls['en']}">
  <link rel="icon" href="/favicon.ico?v=white-1" sizes="16x16 32x32">
  <link rel="icon" type="image/png" href="/favicon-32x32.png?v=white-1" sizes="32x32">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png?v=white-1" sizes="180x180">
  <link rel="manifest" href="/site.webmanifest?v=white-1">
  <link rel="alternate" type="application/rss+xml" href="{'/index.xml' if lang == 'zh' else '/index.en.xml'}" title="Digital Reality" {href_attrs({'zh':'/index.xml','en':'/index.en.xml'})}>
  <link rel="stylesheet" href="/css/site.css">
  <meta property="og:type" content="article">
  <meta property="og:title" content="{title}" data-content-zh="{escape(post['title']['zh'], quote=True)}" data-content-en="{escape(post['title']['en'], quote=True)}">
  <meta property="og:description" content="{summary}" data-content-zh="{escape(post['summary']['zh'], quote=True)}" data-content-en="{escape(post['summary']['en'], quote=True)}">
  <meta property="og:url" content="{BASE + urls[lang]}" data-content-zh="{BASE + urls['zh']}" data-content-en="{BASE + urls['en']}">
  <meta property="article:published_time" content="{post['published']}">
  <meta property="og:image" content="{BASE + post.get('image', '/img/avatar.png')}">
  <meta name="twitter:card" content="summary">
  <script src="/js/site.js" defer></script>'''
    controls = f'''<div class="language-switch" role="group" aria-label="{'界面语言' if lang == 'zh' else 'Interface language'}" data-i18n-aria-label="language">
    <a href="{urls['zh']}" data-locale="zh" lang="zh-Hans" aria-label="使用中文界面"{' aria-current="true"' if lang == 'zh' else ''}>中文</a>
    <span aria-hidden="true">/</span>
    <a href="{urls['en']}" data-locale="en" lang="en" aria-label="Use English interface"{' aria-current="true"' if lang == 'en' else ''}>EN</a>
  </div>'''
    page = template.substitute(html_lang=LANGS[lang], locale=lang, url_zh=urls['zh'], url_en=urls['en'], head=head, language_switch=controls, articles='\n      '.join(article(post, key, key == lang) for key in LANGS))
    if lang == 'en':
        labels = {'skip':'Skip to content', 'about':'About', 'blogs':'Blogs', 'creations':'Creations', 'backBlogs':'← Blogs', 'originalPost':'Originally published on WordPress', 'watchVideo':'Watch on YouTube', 'inspired':'Layout inspired by', 'counterLabel':'Site views'}
        page = re.sub(r'(<[a-z][^>]*data-i18n="([^"]+)"[^>]*>)([^<]*)(</[^>]+>)', lambda m: m[1] + escape(labels.get(m[2], m[3])) + m[4], page)
        page = page.replace(' · 需启用 JavaScript',' · JavaScript required').replace('aria-label="主要导航"','aria-label="Main navigation"')
    return page.replace('<!doctype html>', '<!doctype html>\n' + GENERATED, 1)

def entry(post):
    urls = {lang: url(post['slug'], lang) for lang in LANGS}
    links = href_attrs(urls)
    image = ''
    if post.get('image'):
        image = f'<a class="entry-image" href="{urls["en"]}" {links} tabindex="-1" aria-hidden="true"><img src="{escape(post["image"],quote=True)}" alt="" width="128" height="88" loading="lazy"></a>'
    return f'''<article lang="en" data-content-entry data-date="{post['date']}" class="entry{'' if image else ' entry-text-only'}">
{image}
              <div class="entry-copy">
                <div class="entry-heading">
                  <h3><a href="{urls['en']}" {links} {text_attrs(post['title'])}>{escape(post['title']['en'])}</a></h3>
                  <p class="entry-meta"><time data-ui-date datetime="{post['date']}">{post['date']}</time></p>
                </div>
                <p {text_attrs(post['summary'])}>{escape(post['summary']['en'])}</p>
              </div>
            </article>'''

def replace_block(html, name, content):
    start, end = f'<!-- {name}:start -->', f'<!-- {name}:end -->'
    if html.count(start) != 1 or html.count(end) != 1:
        raise ValueError(f'Expected exactly one {name} marker pair')
    before, rest = html.split(start); _, after = rest.split(end)
    return before + start + '\n' + content + '\n          ' + end + after

def feed(posts, lang, path):
    atom = 'http://www.w3.org/2005/Atom'; ET.register_namespace('atom', atom)
    root = ET.Element('rss', {'version': '2.0'}); channel = ET.SubElement(root, 'channel')
    for tag, value in [('title','Digital Reality'),('link',BASE+'/'),('description','博客文章' if lang=='zh' else 'Blog posts'),('language',LANGS[lang]),('copyright','© 2024–2026 Qiang · CC BY-NC-ND 4.0')]:
        ET.SubElement(channel,tag).text = value
    if posts:
        newest = max(datetime.fromisoformat(p['published']) for p in posts)
        ET.SubElement(channel,'lastBuildDate').text = format_datetime(newest)
    ET.SubElement(channel, f'{{{atom}}}link', {'href':BASE+'/'+path, 'rel':'self', 'type':'application/rss+xml'})
    for post in posts:
        item = ET.SubElement(channel,'item'); target=BASE+url(post['slug'],lang)
        for tag,value in [('title',post['title'][lang]),('link',target),('pubDate',format_datetime(datetime.fromisoformat(post['published']))),('guid',target),('description',post['summary'][lang])]:
            ET.SubElement(item,tag).text=value
    ET.indent(root,space='  ')
    return ET.tostring(root,encoding='unicode',xml_declaration=True)+'\n'

def build(root=ROOT, check=False):
    root = Path(root)
    posts = load_posts(root)
    template = Template((root/'templates/post.html').read_text())
    outputs = {}
    for post in posts:
        for lang in LANGS:
            outputs[url(post['slug'],lang).lstrip('/')+'index.html'] = render_page(post,lang,template)
    article_paths = sorted(outputs)
    entries = [entry(post) for post in posts]
    outputs['posts/index.html'] = replace_block((root/'posts/index.html').read_text(),'blogs','\n'.join(entries))
    homepage = replace_block((root/'index.html').read_text(),'recent-blogs','\n'.join(entries[:8]))
    creations = re.findall(r'<article\b.*?</article>',(root/'creations/index.html').read_text(),re.S)
    creations.sort(key=lambda a:date.fromisoformat(re.search(r'data-date="([^"]+)"',a)[1]),reverse=True)
    outputs['index.html'] = replace_block(homepage,'recent-creations','\n'.join(creations[:4]))
    for lang,suffix in [('zh',''),('en','.en')]:
        for path in [f'index{suffix}.xml',f'posts/index{suffix}.xml']:
            outputs[path] = feed(posts,lang,path)
    ns='http://www.sitemaps.org/schemas/sitemap/0.9'; ET.register_namespace('',ns)
    sitemap=ET.Element(f'{{{ns}}}urlset')
    for path in ['/', '/posts/', '/creations/']+[url(p['slug'],lang) for p in posts for lang in LANGS]:
        item=ET.SubElement(sitemap,f'{{{ns}}}url'); ET.SubElement(item,f'{{{ns}}}loc').text=BASE+path
    ET.indent(sitemap,space='  ')
    outputs['sitemap.xml']=ET.tostring(sitemap,encoding='unicode',xml_declaration=True)+'\n'
    records=[dict(title=p['title'][lang],summary=p['summary'][lang],content=plain(p['body'][lang]),date=p['published'],permalink=url(p['slug'],lang),section='Blogs',lang=lang) for p in posts for lang in LANGS]
    outputs['index.json']=json.dumps(records,ensure_ascii=False,separators=(',',':'))+'\n'
    manifest=root/'.generated-posts.json'
    previous=json.loads(manifest.read_text()) if manifest.exists() else []
    stale=set(previous)-set(article_paths)
    for path in stale:
        if not re.fullmatch(r'(en/)?posts/[a-z0-9][a-z0-9_-]*/index\.html',path):
            raise ValueError(f'Invalid generated path: {path}')
        target=root/path
        if target.exists() and GENERATED not in target.read_text():
            raise ValueError(f'Refusing to remove a file not owned by the generator: {path}')
    outputs['.generated-posts.json']=json.dumps(article_paths,indent=2)+'\n'
    different=[path for path,content in outputs.items() if not (root/path).exists() or (root/path).read_text()!=content]
    if check:
        if different or any((root/path).exists() for path in stale):
            raise ValueError('Generated files are out of date. Run build_posts.py: '+', '.join(different+sorted(stale)))
    else:
        # All content and templates have been validated before touching generated files.
        for path,content in outputs.items():
            target=root/path; target.parent.mkdir(parents=True,exist_ok=True)
            if not target.exists() or target.read_text()!=content:
                target.write_text(content)
        for path in stale:
            (root/path).unlink(missing_ok=True)
    print(f'{"Checked" if check else "Built"} {len(posts)} posts × 2 languages; homepage, archive, RSS and sitemap are current.')
    return outputs

def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true',help='Fail if generated files differ; do not write anything')
    args=parser.parse_args()
    try: build(check=args.check)
    except (ValueError, KeyError, OSError) as error:
        sys.exit(f'Build failed: {error}')

if __name__=='__main__': main()
